import type { Appointment } from "@/types/appointment";

export const appointments: Appointment[] = [
  {
    id: "appointment-001",
    patient: {
      id: "patient-001",
      name: "Maya Patel",
      initials: "MP",
      age: 34,
    },
    clinician: "Dr. Aman",
    specialty: "Cardiology",
    startsAt: "2026-09-25T10:00:00+05:30",
    durationMinutes: 30,
    status: "upcoming",
    consultationType: "online",
    reason: "Regular heart health follow-up",
    room: "Online Consultation",
  },
  {
    id: "appointment-002",
    patient: {
      id: "patient-002",
      name: "Ethan Brooks",
      initials: "EB",
      age: 41,
    },
    clinician: "Dr. Narendra",
    specialty: "Dermatology",
    startsAt: "2026-09-24T11:30:00+05:30",
    durationMinutes: 30,
    status: "confirmed",
    consultationType: "in-person",
    reason: "Skin allergy consultation",
    room: "Clinic Room 204",
  },
  {
    id: "appointment-003",
    patient: {
      id: "patient-001",
      name: "Maya Patel",
      initials: "MP",
      age: 34,
    },
    clinician: "Dr. Anika Rao",
    specialty: "General Medicine",
    startsAt: "2026-09-20T09:30:00+05:30",
    durationMinutes: 30,
    status: "completed",
    consultationType: "in-person",
    reason: "Routine health check-up",
    room: "Clinic Room 102",
  },
  {
    id: "appointment-004",
    patient: {
      id: "patient-002",
      name: "Ethan Brooks",
      initials: "EB",
      age: 41,
    },
    clinician: "Dr. Aman",
    specialty: "Cardiology",
    startsAt: "2026-09-19T15:00:00+05:30",
    durationMinutes: 30,
    status: "cancelled",
    consultationType: "online",
    reason: "Follow-up consultation",
    room: "Online Consultation",
    actionBy: "patient",
    actionType: "cancelled",
    actionReason: "Patient was unavailable at the scheduled time.",
  },
  {
    id: "appointment-005",
    patient: {
      id: "patient-001",
      name: "Maya Patel",
      initials: "MP",
      age: 34,
    },
    clinician: "Dr. Narendra",
    specialty: "Dermatology",
    startsAt: "2026-09-23T16:00:00+05:30",
    durationMinutes: 30,
    status: "confirmed",
    consultationType: "online",
    reason: "Medication follow-up",
    room: "Online Consultation",
    actionBy: "doctor",
    actionType: "rescheduled",
    actionReason: "Doctor requested a time change due to an urgent consultation.",
  },
  {
    id: "appointment-006",
    patient: {
      id: "patient-002",
      name: "Ethan Brooks",
      initials: "EB",
      age: 41,
    },
    clinician: "Dr. Anika Rao",
    specialty: "General Medicine",
    startsAt: "2026-09-21T12:00:00+05:30",
    durationMinutes: 30,
    status: "pending",
    consultationType: "in-person",
    reason: "Initial general consultation",
    room: "Clinic Room 106",
  },
  {
    id: "appointment-007",
    patient: {
      id: "patient-001",
      name: "Maya Patel",
      initials: "MP",
      age: 34,
    },
    clinician: "Dr. Aman",
    specialty: "Cardiology",
    startsAt: "2026-09-18T10:30:00+05:30",
    durationMinutes: 30,
    actualEndAt: "2026-09-18T11:05:00+05:30",
    status: "completed",
    consultationType: "online",
    reason: "Detailed cardiac consultation",
    room: "Online Consultation",
  },
  {
    id: "appointment-008",
    patient: {
      id: "patient-002",
      name: "Ethan Brooks",
      initials: "EB",
      age: 41,
    },
    clinician: "Dr. Narendra",
    specialty: "Dermatology",
    startsAt: "2026-09-17T14:00:00+05:30",
    durationMinutes: 30,
    status: "completed",
    consultationType: "in-person",
    reason: "Dermatology review",
    room: "Clinic Room 204",
  },
];
