import type { AuditLog } from "@/types/audit-log";

export const auditLogs: AuditLog[] = [
  {
    id: "audit-001",
    actorName: "Admin",
    actorRole: "admin",
    action: "doctor-approved",
    affectedEntity: "Dr. Aman",
    entityType: "doctor",
    timestamp: "2026-09-23T10:15:00+05:30",
  },
  {
    id: "audit-002",
    actorName: "Admin",
    actorRole: "admin",
    action: "appointment-confirmed",
    affectedEntity: "Appointment #appointment-002",
    entityType: "appointment",
    timestamp: "2026-09-23T10:42:00+05:30",
  },
  {
    id: "audit-003",
    actorName: "Admin",
    actorRole: "admin",
    action: "payment-refunded",
    affectedEntity: "Payment for appointment-003",
    entityType: "payment",
    timestamp: "2026-09-23T11:05:00+05:30",
  },
  {
    id: "audit-004",
    actorName: "Admin",
    actorRole: "admin",
    action: "doctor-rejected",
    affectedEntity: "Dr. Sample",
    entityType: "doctor",
    timestamp: "2026-09-23T11:28:00+05:30",
  },
  {
    id: "audit-005",
    actorName: "Admin",
    actorRole: "admin",
    action: "appointment-cancelled",
    affectedEntity: "Appointment #appointment-004",
    entityType: "appointment",
    timestamp: "2026-09-23T12:10:00+05:30",
  },
  {
    id: "audit-006",
    actorName: "Shivam",
    actorRole: "user",
    action: "profile-updated",
    affectedEntity: "Patient Profile",
    entityType: "patient",
    timestamp: "2026-09-23T12:34:00+05:30",
  },
  {
    id: "audit-007",
    actorName: "Admin",
    actorRole: "admin",
    action: "doctor-activated",
    affectedEntity: "Dr. Anika Rao",
    entityType: "doctor",
    timestamp: "2026-09-23T13:02:00+05:30",
  },
  {
    id: "audit-008",
    actorName: "Admin",
    actorRole: "admin",
    action: "doctor-deactivated",
    affectedEntity: "Dr. Narendra",
    entityType: "doctor",
    timestamp: "2026-09-23T13:25:00+05:30",
  },
  {
    id: "audit-009",
    actorName: "Maya Patel",
    actorRole: "user",
    action: "patient-updated",
    affectedEntity: "Patient Profile",
    entityType: "patient",
    timestamp: "2026-09-23T14:10:00+05:30",
  },
  {
    id: "audit-010",
    actorName: "Admin",
    actorRole: "admin",
    action: "appointment-confirmed",
    affectedEntity: "Appointment #appointment-005",
    entityType: "appointment",
    timestamp: "2026-09-23T14:45:00+05:30",
  },
];
