import type { Doctor } from "@/types/doctor";

export const doctors: Doctor[] = [
  {
    id: "doctor-aman",
    name: "Dr. Aman",
    status: "active",
    specialty: "General Medicine",
    qualification: "MBBS, MD",
    experienceYears: 8,
    email: "aman@example.com",
    phone: "+91 9876543210",
    hospital: "City Care Hospital",
    location: "Delhi",
    consultationFee: 500,
    onlineFee: 500,
    inPersonFee: 600,
    bio: "Experienced general physician providing comprehensive healthcare and preventive care.",
    qualificationDocument: "aman-qualification.pdf",
    licenseDocument: "aman-medical-license.pdf",
  },
  {
    id: "doctor-narendra",
    name: "Dr. Narendra",
    status: "active",
    specialty: "Cardiology",
    qualification: "MBBS, MD, DM",
    experienceYears: 10,
    email: "narendra@example.com",
    phone: "+91 9876543211",
    hospital: "Heart Care Hospital",
    location: "Delhi",
    consultationFee: 700,
    onlineFee: 700,
    inPersonFee: 850,
    bio: "Cardiology specialist focused on heart health, diagnosis, and long-term patient care.",
    qualificationDocument: "narendra-qualification.pdf",
    licenseDocument: "narendra-medical-license.pdf",
  },
  {
    id: "doctor-anika",
    name: "Dr. Anika Rao",
    status: "inactive",
    specialty: "General Medicine",
    qualification: "MBBS, MD",
    experienceYears: 12,
    email: "anika@example.com",
    phone: "+91 9876543212",
    hospital: "Sunrise Medical Center",
    location: "Mumbai",
    consultationFee: 600,
    onlineFee: 600,
    inPersonFee: 750,
    bio: "General medicine specialist with extensive experience in primary and preventive healthcare.",
    qualificationDocument: "anika-qualification.pdf",
    licenseDocument: "anika-medical-license.pdf",
  },
];